-- Stock Agent schema for Supabase.
-- Paste into: Supabase → SQL Editor → New query → Run
-- After this, reload the site. Analysis rows appear only after the Docker agent
-- writes to THIS same database.

CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS watchlist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    market VARCHAR(8) NOT NULL,
    name VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_watchlist_symbol UNIQUE (symbol)
);

CREATE TABLE IF NOT EXISTS analysis_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(16) NOT NULL,
    mode VARCHAR(16) NOT NULL DEFAULT 'watchlist',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS signals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES analysis_runs (id),
    symbol VARCHAR(32) NOT NULL,
    market VARCHAR(8) NOT NULL,
    action VARCHAR(8) NOT NULL,
    horizon VARCHAR(8) NOT NULL DEFAULT 'SHORT',
    source VARCHAR(16) NOT NULL DEFAULT 'WATCHLIST',
    confidence DOUBLE PRECISION NOT NULL,
    entry_hint DOUBLE PRECISION,
    stop_loss DOUBLE PRECISION,
    take_profit DOUBLE PRECISION,
    holding_period_hint VARCHAR(64),
    rationale TEXT NOT NULL DEFAULT '',
    raw_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_signals_run_id ON signals (run_id);
CREATE INDEX IF NOT EXISTS ix_signals_symbol ON signals (symbol);
CREATE INDEX IF NOT EXISTS ix_signals_horizon ON signals (horizon);

CREATE TABLE IF NOT EXISTS portfolio_positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    market VARCHAR(8) NOT NULL,
    name VARCHAR(128) NOT NULL DEFAULT '',
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    stop_loss DOUBLE PRECISION,
    take_profit DOUBLE PRECISION,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_portfolio_user_symbol UNIQUE (user_id, symbol)
);

CREATE INDEX IF NOT EXISTS ix_portfolio_positions_user_id ON portfolio_positions (user_id);

CREATE TABLE IF NOT EXISTS portfolio_cash (
    user_id UUID NOT NULL PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    cash_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE portfolio_positions ADD COLUMN IF NOT EXISTS stop_loss DOUBLE PRECISION;
ALTER TABLE portfolio_positions ADD COLUMN IF NOT EXISTS take_profit DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS kis_credentials (
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    account_key VARCHAR(16) NOT NULL DEFAULT '',
    environment VARCHAR(8) NOT NULL DEFAULT 'real',
    account_hint VARCHAR(16) NOT NULL DEFAULT '',
    ciphertext TEXT NOT NULL,
    nonce TEXT NOT NULL,
    auth_tag TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT kis_credentials_pkey PRIMARY KEY (user_id, account_key)
);

ALTER TABLE kis_credentials ADD COLUMN IF NOT EXISTS account_key VARCHAR(16) NOT NULL DEFAULT '';
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.kis_credentials'::regclass
          AND contype = 'p'
          AND pg_get_constraintdef(oid) LIKE '%user_id%'
          AND pg_get_constraintdef(oid) NOT LIKE '%account_key%'
    ) THEN
        ALTER TABLE kis_credentials DROP CONSTRAINT kis_credentials_pkey;
        ALTER TABLE kis_credentials ADD CONSTRAINT kis_credentials_pkey PRIMARY KEY (user_id, account_key);
    END IF;
END $$;

UPDATE alembic_version SET version_num = '0008_research_workspace'
WHERE version_num IN ('0004_user_portfolio', '0005_kis_and_targets', '0006_kis_accounts', '0007_analysis_requests');
INSERT INTO alembic_version (version_num)
SELECT '0008_research_workspace'
WHERE NOT EXISTS (SELECT 1 FROM alembic_version);

CREATE TABLE IF NOT EXISTS analysis_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    mode VARCHAR(16) NOT NULL DEFAULT 'scan',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS ix_analysis_requests_status ON analysis_requests (status);

ALTER TABLE portfolio_cash ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kis_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS portfolio_cash_select ON portfolio_cash;
DROP POLICY IF EXISTS portfolio_cash_insert ON portfolio_cash;
DROP POLICY IF EXISTS portfolio_cash_update ON portfolio_cash;
DROP POLICY IF EXISTS portfolio_positions_select ON portfolio_positions;
DROP POLICY IF EXISTS portfolio_positions_insert ON portfolio_positions;
DROP POLICY IF EXISTS portfolio_positions_update ON portfolio_positions;
DROP POLICY IF EXISTS portfolio_positions_delete ON portfolio_positions;
DROP POLICY IF EXISTS kis_credentials_select ON kis_credentials;
DROP POLICY IF EXISTS kis_credentials_insert ON kis_credentials;
DROP POLICY IF EXISTS kis_credentials_update ON kis_credentials;
DROP POLICY IF EXISTS kis_credentials_delete ON kis_credentials;
DROP POLICY IF EXISTS signals_select ON signals;
DROP POLICY IF EXISTS analysis_runs_select ON analysis_runs;
DROP POLICY IF EXISTS analysis_requests_select ON analysis_requests;
DROP POLICY IF EXISTS analysis_requests_insert ON analysis_requests;

CREATE POLICY portfolio_cash_select ON portfolio_cash
    FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY portfolio_cash_insert ON portfolio_cash
    FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY portfolio_cash_update ON portfolio_cash
    FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY portfolio_positions_select ON portfolio_positions
    FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY portfolio_positions_insert ON portfolio_positions
    FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY portfolio_positions_update ON portfolio_positions
    FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY portfolio_positions_delete ON portfolio_positions
    FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY kis_credentials_select ON kis_credentials
    FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY kis_credentials_insert ON kis_credentials
    FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY kis_credentials_update ON kis_credentials
    FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY kis_credentials_delete ON kis_credentials
    FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE POLICY signals_select ON signals
    FOR SELECT TO authenticated USING (true);
CREATE POLICY analysis_runs_select ON analysis_runs
    FOR SELECT TO authenticated USING (true);

CREATE POLICY analysis_requests_select ON analysis_requests
    FOR SELECT TO authenticated USING (true);
CREATE POLICY analysis_requests_insert ON analysis_requests
    FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

GRANT SELECT ON analysis_runs, signals TO authenticated;
GRANT SELECT, INSERT ON analysis_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON portfolio_cash, portfolio_positions, kis_credentials TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE analysis_requests_id_seq TO authenticated;

CREATE TABLE IF NOT EXISTS user_company_research (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    market VARCHAR(8) NOT NULL,
    name VARCHAR(128) NOT NULL DEFAULT '',
    watching BOOLEAN NOT NULL DEFAULT true,
    study_progress DOUBLE PRECISION NOT NULL DEFAULT 0,
    overall_sentiment VARCHAR(16) NOT NULL DEFAULT 'NEUTRAL',
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_studied_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_company_research UNIQUE (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS research_conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    title VARCHAR(256) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INTEGER NOT NULL REFERENCES research_conversations (id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    structured_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    title VARCHAR(256) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    new_learnings JSONB NOT NULL DEFAULT '[]'::jsonb,
    investment_idea TEXT NOT NULL DEFAULT '',
    things_to_check JSONB NOT NULL DEFAULT '[]'::jsonb,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    related_thesis_id INTEGER,
    source_conversation_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS investment_theses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    title VARCHAR(256) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    sentiment VARCHAR(16) NOT NULL DEFAULT 'NEUTRAL',
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    evidence TEXT NOT NULL DEFAULT '',
    counter_evidence TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_reviewed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS thesis_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thesis_id INTEGER NOT NULL REFERENCES investment_theses (id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    previous_status VARCHAR(16),
    new_status VARCHAR(16),
    previous_sentiment VARCHAR(16),
    new_sentiment VARCHAR(16),
    previous_confidence DOUBLE PRECISION,
    new_confidence DOUBLE PRECISION,
    reason TEXT NOT NULL DEFAULT '',
    source_type VARCHAR(32) NOT NULL DEFAULT 'USER',
    source_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    title VARCHAR(512) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    event_date DATE NOT NULL DEFAULT CURRENT_DATE,
    source_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_timeline (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    event_id INTEGER,
    event_type VARCHAR(32) NOT NULL,
    title VARCHAR(512) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    event_date DATE NOT NULL DEFAULT CURRENT_DATE,
    ai_opinion TEXT NOT NULL DEFAULT '',
    user_opinion TEXT NOT NULL DEFAULT '',
    related_thesis_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_changes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    title VARCHAR(512) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    related_thesis_id INTEGER,
    impact VARCHAR(16) NOT NULL DEFAULT 'NEUTRAL',
    impact_score INTEGER NOT NULL DEFAULT 0,
    proposed_status VARCHAR(16),
    proposed_sentiment VARCHAR(16),
    proposed_confidence DOUBLE PRECISION,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    source_type VARCHAR(32) NOT NULL DEFAULT 'CHAT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS study_topics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(64) NOT NULL,
    title VARCHAR(256) NOT NULL,
    prompt TEXT NOT NULL,
    order_no INTEGER NOT NULL,
    CONSTRAINT uq_study_topics_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS user_study_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    study_topic_id INTEGER NOT NULL REFERENCES study_topics (id) ON DELETE CASCADE,
    completed BOOLEAN NOT NULL DEFAULT false,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_user_study_progress UNIQUE (user_id, symbol, study_topic_id)
);

CREATE TABLE IF NOT EXISTS research_notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(256) NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    read_yn BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_judgments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    symbol VARCHAR(32) NOT NULL,
    statement TEXT NOT NULL,
    rationale TEXT NOT NULL DEFAULT '',
    price_at_time DOUBLE PRECISION,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_judgment_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judgment_id INTEGER NOT NULL REFERENCES research_judgments (id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    statement TEXT NOT NULL,
    rationale TEXT NOT NULL DEFAULT '',
    price_at_time DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ucr_user ON user_company_research (user_id);
CREATE INDEX IF NOT EXISTS ix_research_conv_user_symbol ON research_conversations (user_id, symbol);
CREATE INDEX IF NOT EXISTS ix_research_msg_conv ON research_messages (conversation_id);
CREATE INDEX IF NOT EXISTS ix_research_notes_user_symbol ON research_notes (user_id, symbol);
CREATE INDEX IF NOT EXISTS ix_theses_user_symbol ON investment_theses (user_id, symbol);
CREATE INDEX IF NOT EXISTS ix_thesis_history_thesis ON thesis_history (thesis_id);
CREATE INDEX IF NOT EXISTS ix_company_events_symbol_date ON company_events (symbol, event_date);
CREATE INDEX IF NOT EXISTS ix_timeline_user_symbol ON research_timeline (user_id, symbol, event_date);
CREATE INDEX IF NOT EXISTS ix_changes_user_symbol ON research_changes (user_id, symbol, status);
CREATE INDEX IF NOT EXISTS ix_notifications_user ON research_notifications (user_id, read_yn);
CREATE INDEX IF NOT EXISTS ix_judgments_user_symbol ON research_judgments (user_id, symbol);

INSERT INTO study_topics (category, title, prompt, order_no) VALUES
    ('business', '회사가 어떻게 돈을 버는지', '이 회사가 어떻게 돈을 버는지 핵심 수익원을 단계적으로 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 1),
    ('business', '주요 사업부', '주요 사업부를 나누고 각 사업이 전체에서 차지하는 역할을 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 2),
    ('financials', '매출 구조', '매출 구조를 제품/지역/고객 관점에서 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 3),
    ('financials', '영업이익 구조', '영업이익이 어디서 나고 무엇이 마진을 좌우하는지 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 4),
    ('financials', '최근 5년 실적', '최근 실적 추세를 성장, 수익성, 변동성 관점으로 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 5),
    ('competition', '경쟁사', '핵심 경쟁사와 경쟁 구도를 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 6),
    ('competition', '시장 점유율', '시장 점유율과 점유율 변화의 투자 의미를 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 7),
    ('governance', '경영진', '경영진과 자본 배분 스타일이 투자에 어떤 의미가 있는지 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 8),
    ('growth', 'CAPEX', 'CAPEX 규모와 방향이 미래 이익에 주는 영향을 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 9),
    ('customers', '주요 고객', '주요 고객 의존도와 그 리스크를 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 10),
    ('valuation', '밸류에이션', '현재 밸류에이션이 비싼지 싼지, 어떤 가정을 반영하는지 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 11),
    ('catalyst', '성장 Catalyst', '앞으로 주가/기업가치를 움직일 촉매를 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 12),
    ('risk', '리스크', '이 회사 투자의 핵심 리스크와 논리가 깨지는 조건을 설명해 주세요. 마지막에 확인 질문을 하나 주세요.', 13),
    ('thesis', '투자 Thesis', '이 회사 투자 논리를 어떻게 세워야 하는지 프레임을 제시해 주세요. 마지막에 확인 질문을 하나 주세요.', 14)
ON CONFLICT (title) DO NOTHING;

ALTER TABLE user_company_research ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE investment_theses ENABLE ROW LEVEL SECURITY;
ALTER TABLE thesis_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_study_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_judgments ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_judgment_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ucr_all ON user_company_research;
CREATE POLICY ucr_all ON user_company_research FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS research_conv_all ON research_conversations;
CREATE POLICY research_conv_all ON research_conversations FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS research_msg_all ON research_messages;
CREATE POLICY research_msg_all ON research_messages FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS research_notes_all ON research_notes;
CREATE POLICY research_notes_all ON research_notes FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS theses_all ON investment_theses;
CREATE POLICY theses_all ON investment_theses FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS thesis_history_all ON thesis_history;
CREATE POLICY thesis_history_all ON thesis_history FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS company_events_select ON company_events;
CREATE POLICY company_events_select ON company_events FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS company_events_insert ON company_events;
CREATE POLICY company_events_insert ON company_events FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS timeline_all ON research_timeline;
CREATE POLICY timeline_all ON research_timeline FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS changes_all ON research_changes;
CREATE POLICY changes_all ON research_changes FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS study_topics_select ON study_topics;
CREATE POLICY study_topics_select ON study_topics FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS study_progress_all ON user_study_progress;
CREATE POLICY study_progress_all ON user_study_progress FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS notifications_all ON research_notifications;
CREATE POLICY notifications_all ON research_notifications FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS judgments_all ON research_judgments;
CREATE POLICY judgments_all ON research_judgments FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS judgment_versions_all ON research_judgment_versions;
CREATE POLICY judgment_versions_all ON research_judgment_versions FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON user_company_research, research_conversations, research_messages, research_notes, investment_theses, thesis_history, research_timeline, research_changes, user_study_progress, research_notifications, research_judgments, research_judgment_versions TO authenticated;
GRANT SELECT, INSERT ON company_events TO authenticated;
GRANT SELECT ON study_topics TO authenticated;

NOTIFY pgrst, 'reload schema';
