"""Web-triggered analysis requests for the Docker scheduler.

Revision ID: 0007_analysis_requests
Revises: 0006_kis_accounts
Create Date: 2026-08-18
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0007_analysis_requests"
down_revision: Union[str, None] = "0006_kis_accounts"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS analysis_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    mode VARCHAR(16) NOT NULL DEFAULT 'scan',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT
)
"""

RLS_STATEMENTS = (
    "ALTER TABLE analysis_requests ENABLE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS analysis_requests_select ON analysis_requests",
    "DROP POLICY IF EXISTS analysis_requests_insert ON analysis_requests",
    "CREATE POLICY analysis_requests_select ON analysis_requests "
    "FOR SELECT TO authenticated USING (true)",
    "CREATE POLICY analysis_requests_insert ON analysis_requests "
    "FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid())",
    "GRANT SELECT, INSERT ON analysis_requests TO authenticated",
    "GRANT USAGE, SELECT ON SEQUENCE analysis_requests_id_seq TO authenticated",
    "NOTIFY pgrst, 'reload schema'",
)


def upgrade() -> None:
    op.execute(sa.text(CREATE_TABLE_SQL))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_analysis_requests_status ON analysis_requests (status)"))
    conn = op.get_bind()
    has_auth = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'auth')"
        )
    ).scalar()
    if has_auth:
        op.execute(
            sa.text(
                "ALTER TABLE analysis_requests DROP CONSTRAINT IF EXISTS fk_analysis_requests_user"
            )
        )
        op.execute(
            sa.text(
                "ALTER TABLE analysis_requests DROP CONSTRAINT IF EXISTS analysis_requests_user_id_fkey"
            )
        )
        op.execute(
            sa.text(
                "ALTER TABLE analysis_requests ADD CONSTRAINT fk_analysis_requests_user "
                "FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE"
            )
        )
        for statement in RLS_STATEMENTS:
            op.execute(sa.text(statement))


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS ix_analysis_requests_status"))
    op.execute(sa.text("DROP TABLE IF EXISTS analysis_requests"))
