"""Dividend wealth agent tables.

Revision ID: 0009_dividend_agent
Revises: 0008_research_workspace
Create Date: 2026-09-07
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0009_dividend_agent"
down_revision: Union[str, None] = "0008_research_workspace"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS dividend_goals (
    user_id UUID PRIMARY KEY,
    target_monthly_dividend DOUBLE PRECISION NOT NULL DEFAULT 0,
    target_is_after_tax BOOLEAN NOT NULL DEFAULT true,
    current_investable_assets DOUBLE PRECISION NOT NULL DEFAULT 0,
    monthly_contribution DOUBLE PRECISION NOT NULL DEFAULT 0,
    investment_horizon_years INTEGER NOT NULL DEFAULT 10,
    risk_level VARCHAR(16) NOT NULL DEFAULT 'BALANCED',
    country VARCHAR(8) NOT NULL DEFAULT 'BOTH',
    reinvest_dividends BOOLEAN NOT NULL DEFAULT true,
    onboarded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dividend_asset_roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'CORE',
    target_weight_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dividend_asset_roles_user_symbol UNIQUE (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS dividend_monthly_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    plan_month DATE NOT NULL,
    total_contribution DOUBLE PRECISION NOT NULL DEFAULT 0,
    allocations JSONB NOT NULL DEFAULT '[]'::jsonb,
    ai_explanation TEXT NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dividend_monthly_plans_user_month UNIQUE (user_id, plan_month)
);

CREATE TABLE IF NOT EXISTS dividend_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    structured_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dividend_asset_roles_user ON dividend_asset_roles (user_id);
CREATE INDEX IF NOT EXISTS ix_dividend_monthly_plans_user ON dividend_monthly_plans (user_id, plan_month);
CREATE INDEX IF NOT EXISTS ix_dividend_messages_user ON dividend_messages (user_id, created_at);
"""

RLS_STATEMENTS = (
    "ALTER TABLE dividend_goals ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE dividend_asset_roles ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE dividend_monthly_plans ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE dividend_messages ENABLE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS dividend_goals_all ON dividend_goals",
    "CREATE POLICY dividend_goals_all ON dividend_goals FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid())",
    "DROP POLICY IF EXISTS dividend_asset_roles_all ON dividend_asset_roles",
    "CREATE POLICY dividend_asset_roles_all ON dividend_asset_roles FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid())",
    "DROP POLICY IF EXISTS dividend_monthly_plans_all ON dividend_monthly_plans",
    "CREATE POLICY dividend_monthly_plans_all ON dividend_monthly_plans FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid())",
    "DROP POLICY IF EXISTS dividend_messages_all ON dividend_messages",
    "CREATE POLICY dividend_messages_all ON dividend_messages FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid())",
    "GRANT SELECT, INSERT, UPDATE, DELETE ON dividend_goals, dividend_asset_roles, dividend_monthly_plans, dividend_messages TO authenticated",
    "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated",
    "NOTIFY pgrst, 'reload schema'",
)

DROP_SQL = """
DROP TABLE IF EXISTS dividend_messages CASCADE;
DROP TABLE IF EXISTS dividend_monthly_plans CASCADE;
DROP TABLE IF EXISTS dividend_asset_roles CASCADE;
DROP TABLE IF EXISTS dividend_goals CASCADE;
"""


def upgrade() -> None:
    op.execute(sa.text(CREATE_TABLES_SQL))
    conn = op.get_bind()
    has_auth = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'auth')"
        )
    ).scalar()
    if has_auth:
        for table in (
            "dividend_goals",
            "dividend_asset_roles",
            "dividend_monthly_plans",
            "dividend_messages",
        ):
            op.execute(
                sa.text(
                    f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS fk_{table}_user"
                )
            )
            op.execute(
                sa.text(
                    f"ALTER TABLE {table} ADD CONSTRAINT fk_{table}_user "
                    "FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE"
                )
            )
        for statement in RLS_STATEMENTS:
            op.execute(sa.text(statement))


def downgrade() -> None:
    op.execute(sa.text(DROP_SQL))
